#############################################################################
# Makefile for building: square-root
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat Jun 5 22:19:41 2010
# Project:  square-root.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile square-root.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Ialgorithm -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = about.cpp \
		actioncurve.cpp \
		main.cpp \
		mainwindow.cpp \
		plot.cpp \
		plotcurve.cpp \
		polinomial.cpp \
		wizard.cpp \
		wizardpages.cpp \
		algorithm/curve.cpp \
		algorithm/minimosquadrados.cpp \
		algorithm/point.cpp moc_about.cpp \
		moc_actioncurve.cpp \
		moc_mainwindow.cpp \
		moc_wizard.cpp \
		moc_wizardpages.cpp \
		qrc_images.cpp
OBJECTS       = about.o \
		actioncurve.o \
		main.o \
		mainwindow.o \
		plot.o \
		plotcurve.o \
		polinomial.o \
		wizard.o \
		wizardpages.o \
		curve.o \
		minimosquadrados.o \
		point.o \
		moc_about.o \
		moc_actioncurve.o \
		moc_mainwindow.o \
		moc_wizard.o \
		moc_wizardpages.o \
		qrc_images.o
DIST          = /usr/mkspecs/common/g++.conf \
		/usr/mkspecs/common/unix.conf \
		/usr/mkspecs/common/linux.conf \
		/usr/mkspecs/qconfig.pri \
		/usr/mkspecs/features/qt_functions.prf \
		/usr/mkspecs/features/qt_config.prf \
		/usr/mkspecs/features/exclusive_builds.prf \
		/usr/mkspecs/features/default_pre.prf \
		/usr/mkspecs/features/release.prf \
		/usr/mkspecs/features/default_post.prf \
		/usr/mkspecs/features/warn_on.prf \
		/usr/mkspecs/modules/qt_webkit_version.pri \
		/usr/mkspecs/features/qt.prf \
		/usr/mkspecs/features/unix/thread.prf \
		/usr/mkspecs/features/moc.prf \
		/usr/mkspecs/features/resources.prf \
		/usr/mkspecs/features/uic.prf \
		/usr/mkspecs/features/yacc.prf \
		/usr/mkspecs/features/lex.prf \
		/usr/mkspecs/features/include_source_dir.prf \
		square-root.pro
QMAKE_TARGET  = square-root
DESTDIR       = 
TARGET        = square-root

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: square-root.pro  /usr/mkspecs/linux-g++/qmake.conf /usr/mkspecs/common/g++.conf \
		/usr/mkspecs/common/unix.conf \
		/usr/mkspecs/common/linux.conf \
		/usr/mkspecs/qconfig.pri \
		/usr/mkspecs/features/qt_functions.prf \
		/usr/mkspecs/features/qt_config.prf \
		/usr/mkspecs/features/exclusive_builds.prf \
		/usr/mkspecs/features/default_pre.prf \
		/usr/mkspecs/features/release.prf \
		/usr/mkspecs/features/default_post.prf \
		/usr/mkspecs/features/warn_on.prf \
		/usr/mkspecs/modules/qt_webkit_version.pri \
		/usr/mkspecs/features/qt.prf \
		/usr/mkspecs/features/unix/thread.prf \
		/usr/mkspecs/features/moc.prf \
		/usr/mkspecs/features/resources.prf \
		/usr/mkspecs/features/uic.prf \
		/usr/mkspecs/features/yacc.prf \
		/usr/mkspecs/features/lex.prf \
		/usr/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile square-root.pro
/usr/mkspecs/common/g++.conf:
/usr/mkspecs/common/unix.conf:
/usr/mkspecs/common/linux.conf:
/usr/mkspecs/qconfig.pri:
/usr/mkspecs/features/qt_functions.prf:
/usr/mkspecs/features/qt_config.prf:
/usr/mkspecs/features/exclusive_builds.prf:
/usr/mkspecs/features/default_pre.prf:
/usr/mkspecs/features/release.prf:
/usr/mkspecs/features/default_post.prf:
/usr/mkspecs/features/warn_on.prf:
/usr/mkspecs/modules/qt_webkit_version.pri:
/usr/mkspecs/features/qt.prf:
/usr/mkspecs/features/unix/thread.prf:
/usr/mkspecs/features/moc.prf:
/usr/mkspecs/features/resources.prf:
/usr/mkspecs/features/uic.prf:
/usr/mkspecs/features/yacc.prf:
/usr/mkspecs/features/lex.prf:
/usr/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile square-root.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/square-root1.0.0 || $(MKDIR) .tmp/square-root1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/square-root1.0.0/ && $(COPY_FILE) --parents about.h actioncurve.h mainwindow.h plot.h plotcurve.h polinomial.h simple.h ui_configpage.h wizard.h wizardpages.h algorithm/curve.h algorithm/minimosquadrados.h algorithm/point.h .tmp/square-root1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/square-root1.0.0/ && $(COPY_FILE) --parents about.cpp actioncurve.cpp main.cpp mainwindow.cpp plot.cpp plotcurve.cpp polinomial.cpp wizard.cpp wizardpages.cpp algorithm/curve.cpp algorithm/minimosquadrados.cpp algorithm/point.cpp .tmp/square-root1.0.0/ && $(COPY_FILE) --parents about.ui .tmp/square-root1.0.0/ && (cd `dirname .tmp/square-root1.0.0` && $(TAR) square-root1.0.0.tar square-root1.0.0 && $(COMPRESS) square-root1.0.0.tar) && $(MOVE) `dirname .tmp/square-root1.0.0`/square-root1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/square-root1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_about.cpp moc_actioncurve.cpp moc_mainwindow.cpp moc_wizard.cpp moc_wizardpages.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_about.cpp moc_actioncurve.cpp moc_mainwindow.cpp moc_wizard.cpp moc_wizardpages.cpp
moc_about.cpp: about.h
	/usr/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

moc_actioncurve.cpp: actioncurve.h
	/usr/bin/moc $(DEFINES) $(INCPATH) actioncurve.h -o moc_actioncurve.cpp

moc_mainwindow.cpp: algorithm/curve.h \
		algorithm/point.h \
		plot.h \
		plotcurve.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_wizard.cpp: algorithm/curve.h \
		algorithm/point.h \
		wizard.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wizard.h -o moc_wizard.cpp

moc_wizardpages.cpp: algorithm/curve.h \
		algorithm/point.h \
		wizardpages.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wizardpages.h -o moc_wizardpages.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		logo/brasao2.png \
		logo/verformatacao.png \
		logo/brasao3.png \
		logo/fisica1.jpg \
		logo/einstein.png \
		logo/jazz.png \
		logo/brasao1.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_about.h
ui_about.h: about.ui
	/usr/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

actioncurve.o: actioncurve.cpp actioncurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actioncurve.o actioncurve.cpp

main.o: main.cpp mainwindow.h \
		algorithm/curve.h \
		algorithm/point.h \
		plot.h \
		plotcurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		algorithm/curve.h \
		algorithm/point.h \
		plot.h \
		plotcurve.h \
		algorithm/minimosquadrados.h \
		actioncurve.h \
		wizard.h \
		polinomial.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

plot.o: plot.cpp polinomial.h \
		algorithm/curve.h \
		algorithm/point.h \
		plot.h \
		plotcurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plot.o plot.cpp

plotcurve.o: plotcurve.cpp plotcurve.h \
		algorithm/curve.h \
		algorithm/point.h \
		polinomial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotcurve.o plotcurve.cpp

polinomial.o: polinomial.cpp polinomial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polinomial.o polinomial.cpp

wizard.o: wizard.cpp wizard.h \
		algorithm/curve.h \
		algorithm/point.h \
		wizardpages.h \
		algorithm/minimosquadrados.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizard.o wizard.cpp

wizardpages.o: wizardpages.cpp wizardpages.h \
		algorithm/curve.h \
		algorithm/point.h \
		algorithm/minimosquadrados.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizardpages.o wizardpages.cpp

curve.o: algorithm/curve.cpp algorithm/curve.h \
		algorithm/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curve.o algorithm/curve.cpp

minimosquadrados.o: algorithm/minimosquadrados.cpp algorithm/minimosquadrados.h \
		algorithm/curve.h \
		algorithm/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minimosquadrados.o algorithm/minimosquadrados.cpp

point.o: algorithm/point.cpp algorithm/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o algorithm/point.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_actioncurve.o: moc_actioncurve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_actioncurve.o moc_actioncurve.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_wizard.o: moc_wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizard.o moc_wizard.cpp

moc_wizardpages.o: moc_wizardpages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizardpages.o moc_wizardpages.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

